apiVersion: apps/v1
kind: Deployment
metadata:
  name: pritunl
  namespace: infrastructure
spec:
  selector:
    matchLabels:
      app: pritunl
  template:
    metadata:
      labels:
        app: pritunl
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image: docker.io/redavtovo/pritunl
          name: pritunl
          imagePullPolicy: Always
          env:
            - name: MONGODB_SERVER
              value: "mongodb"
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 1194
              protocol: UDP
          securityContext:
            privileged: true
